version: "3.9"

services:
  gunbot:
    container_name: gunbot
    #image: gunbot:latest
    build: .
    restart: unless-stopped
    ports:
      - 5555:5000
    environment:
      - TZ=Europe/Vienna
      - PGID=1024
      - PUID=100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/TZ:/etc/timezone:ro
      - "/volume1/docker/gunbot/config/backups:/gunbot/backups"
      - "/volume1/docker/gunbot/config/logs:/gunbot/gunbot_logs"
      - "/volume1/docker/gunbot/config/logs/err.log:/gunbot/err.log"
      - "/volume1/docker/gunbot/config/json:/gunbot/json"
      - "/volume1/docker/gunbot/config/ssl:/gunbot/ssl"
      - "/volume1/docker/gunbot/config/config.js:/gunbot/config.js"
      - "/volume1/docker/gunbot/config/gunbotgui.db:/gunbot/gunbotgui.db"
      - "/volume1/docker/gunbot/config/tgconfig.json:/gunbot/tgconfig.json"
      - "/volume1/docker/gunbot/config/session.json:/gunbot/session.json"
      - "/volume1/docker/gunbot/config/autoconfig.json:/gunbot/autoconfig.json"
      - "/volume1/docker/gunbot/config/conversion.json:/gunbot/conversion.json"
      
